/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_voting_crypto_AESCipher */

#ifndef _Included_com_voting_crypto_AESCipher
#define _Included_com_voting_crypto_AESCipher
#ifdef __cplusplus
extern "C" {
#endif
#undef com_voting_crypto_AESCipher_SIZE
#define com_voting_crypto_AESCipher_SIZE 16L
/*
 * Class:     com_voting_crypto_AESCipher
 * Method:    keyExpansion
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_com_voting_crypto_AESCipher_keyExpansion
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_voting_crypto_AESCipher
 * Method:    crypt
 * Signature: ([B[I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_voting_crypto_AESCipher_crypt
  (JNIEnv *, jobject, jbyteArray, jintArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
